import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve('packages/registry/starters/default/template');

function write(rel, content) {
  const full = path.join(root, rel);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, content);
}

const vitestVersion = '^2.1.0';
const typescriptVersion = '^5.7.2';
const viteVersion = '^6.0.0';
const reactVersion = '^18.3.1';
const reactDomVersion = '^18.3.1';
const typesReactVersion = '^18.3.3';
const typesReactDomVersion = '^18.3.0';
const honoVersion = '^4.6.0';
const wranglerVersion = '^3.62.0';
const workersTypesVersion = '^4.20240620.0';

const files = {
  'docs/ARCHITECTURE.md': `# Architecture

## Overview

This monorepo contains a React/Vite web application, a Hono/Cloudflare Workers API, and shared packages.

## Boundaries

- \`factory-generated\` — files owned and synced by Project Factory.
- \`features\` — product capabilities added by modules.
- \`extensions\` — safe space for manual user extensions.
`,

  'docs/MODULES.md': `# Modules

This project supports Project Factory modules. See the registry for available modules.
`,

  '.project-factory/modules.json': JSON.stringify({ modules: [] }, null, 2) + '\n',

  '.github/workflows/ci.yml': `name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run typecheck
      - run: pnpm run test
      - run: pnpm run build
`,

  '.prettierignore': `node_modules/
dist/
build/
*.log
`,

  'prettier.config.js': `/** @type {import('prettier').Config} */
export default {
  semi: true,
  singleQuote: true,
  trailingComma: 'all',
  printWidth: 100,
};
`,

  'eslint.config.js': `import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: ['node_modules/**', 'dist/**', 'build/**'],
  },
  tseslint.configs.recommended,
  {
    files: ['**/*.{ts,tsx,mjs,cjs}'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
    },
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    },
  }
);
`,

  'package.json': JSON.stringify({
    name: '@workspace/root',
    private: true,
    version: '0.1.0',
    type: 'module',
    scripts: {
      typecheck: 'pnpm -r run typecheck',
      test: 'pnpm -r run test',
      build: 'pnpm -r run build',
      lint: 'eslint .',
      format: 'prettier --write "**/*.{ts,tsx,mjs,cjs,json,md,yml}"',
    },
    devDependencies: {
      '@types/node': '^22.0.0',
      eslint: '^9.0.0',
      prettier: '^3.0.0',
      typescript: typescriptVersion,
      'typescript-eslint': '^8.0.0',
      vitest: vitestVersion,
    },
  }, null, 2) + '\n',

  'pnpm-workspace.yaml': `packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
`,

  'tsconfig.json': JSON.stringify({
    compilerOptions: {
      target: 'ES2022',
      module: 'NodeNext',
      moduleResolution: 'NodeNext',
      lib: ['ES2022', 'DOM', 'DOM.Iterable'],
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      resolveJsonModule: true,
      isolatedModules: true,
      noUnusedLocals: true,
      noUnusedParameters: true,
      noImplicitReturns: true,
      noFallthroughCasesInSwitch: true,
    },
  }, null, 2) + '\n',

  '.env.example': `# Project Factory generated environment variables
NODE_ENV=development
API_PORT=8787
`,

  'README.md': `# {{PROJECT_NAME}}

This project was generated by Project Factory using the **{{PROJECT_STARTER}}** starter.

## Getting Started

\`\`\`bash
pnpm install
pnpm run typecheck
pnpm run test
pnpm run build
\`\`\`
`,

  'apps/web/package.json': JSON.stringify({
    name: '@workspace/web',
    type: 'module',
    version: '0.1.0',
    scripts: {
      dev: 'vite',
      build: 'tsc && vite build',
      typecheck: 'tsc --noEmit',
      test: 'vitest run',
    },
    dependencies: {
      react: reactVersion,
      'react-dom': reactDomVersion,
    },
    devDependencies: {
      '@types/react': typesReactVersion,
      '@types/react-dom': typesReactDomVersion,
      '@vitejs/plugin-react': '^4.3.1',
      typescript: typescriptVersion,
      vite: viteVersion,
      vitest: vitestVersion,
    },
  }, null, 2) + '\n',

  'apps/web/tsconfig.json': JSON.stringify({
    compilerOptions: {
      target: 'ES2022',
      module: 'ESNext',
      moduleResolution: 'Bundler',
      lib: ['ES2022', 'DOM', 'DOM.Iterable'],
      jsx: 'react-jsx',
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      resolveJsonModule: true,
      isolatedModules: true,
      noUnusedLocals: true,
      noUnusedParameters: true,
      noImplicitReturns: true,
      noFallthroughCasesInSwitch: true,
      outDir: './dist',
    },
    include: ['src/**/*'],
  }, null, 2) + '\n',

  'apps/web/vite.config.ts': `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
  },
});
`,

  'apps/web/vitest.config.ts': `import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'node',
  },
});
`,

  'apps/web/index.html': `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{PROJECT_NAME}}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`,

  'apps/web/src/index.css': `body {
  margin: 0;
  font-family: system-ui, sans-serif;
}
`,

  'apps/web/src/main.tsx': `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`,

  'apps/web/src/App.tsx': `import { useState } from 'react';

export default function App() {
  const [count, setCount] = useState(0);

  return (
    <main style={{ padding: '2rem' }}>
      <h1>__PROJECT_NAME__</h1>
      <p>Count: {count}</p>
      <button onClick={() => setCount((c) => c + 1)}>Increment</button>
    </main>
  );
}
`,

  'apps/web/src/App.test.tsx': `import { describe, it, expect } from 'vitest';

describe('App', () => {
  it('renders without crashing', () => {
    expect(true).toBe(true);
  });
});
`,

  'apps/api/package.json': JSON.stringify({
    name: '@workspace/api',
    type: 'module',
    version: '0.1.0',
    scripts: {
      dev: 'wrangler dev',
      deploy: 'wrangler deploy',
      typecheck: 'tsc --noEmit',
      test: 'vitest run',
      build: 'tsc --noEmit',
    },
    dependencies: {
      hono: honoVersion,
    },
    devDependencies: {
      '@cloudflare/workers-types': workersTypesVersion,
      typescript: typescriptVersion,
      vitest: vitestVersion,
      wrangler: wranglerVersion,
    },
  }, null, 2) + '\n',

  'apps/api/tsconfig.json': JSON.stringify({
    compilerOptions: {
      target: 'ES2022',
      module: 'ESNext',
      moduleResolution: 'Bundler',
      lib: ['ES2022'],
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      resolveJsonModule: true,
      isolatedModules: true,
      noUnusedLocals: true,
      noUnusedParameters: true,
      noImplicitReturns: true,
      noFallthroughCasesInSwitch: true,
      types: ['@cloudflare/workers-types'],
    },
    include: ['src/**/*'],
  }, null, 2) + '\n',

  'apps/api/vitest.config.ts': `import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'node',
  },
});
`,

  'apps/api/src/index.ts': `import { Hono } from 'hono';

const app = new Hono();

app.get('/health', (c) => c.json({ status: 'ok' }));

app.get('/', (c) => c.text('Hello from __PROJECT_NAME__ API'));

export default app;
`,

  'apps/api/src/index.test.ts': `import { describe, it, expect } from 'vitest';

describe('api', () => {
  it('is true', () => {
    expect(true).toBe(true);
  });
});
`,

  'packages/contracts/package.json': JSON.stringify({
    name: '@workspace/contracts',
    version: '0.1.0',
    type: 'module',
    main: './dist/index.js',
    types: './dist/index.d.ts',
    scripts: {
      typecheck: 'tsc --noEmit',
      test: 'vitest run',
      build: 'tsc',
    },
    devDependencies: {
      typescript: typescriptVersion,
      vitest: vitestVersion,
    },
  }, null, 2) + '\n',

  'packages/contracts/tsconfig.json': JSON.stringify({
    compilerOptions: {
      target: 'ES2022',
      module: 'NodeNext',
      moduleResolution: 'NodeNext',
      lib: ['ES2022'],
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      resolveJsonModule: true,
      isolatedModules: true,
      declaration: true,
      outDir: './dist',
      rootDir: './src',
    },
    include: ['src/**/*'],
  }, null, 2) + '\n',

  'packages/contracts/vitest.config.ts': `import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'node',
  },
});
`,

  'packages/contracts/src/index.ts': `export interface HealthResponse {
  status: string;
}
`,

  'packages/contracts/src/index.test.ts': `import { describe, it, expect } from 'vitest';
import type { HealthResponse } from './index.js';

describe('contracts', () => {
  it('exports a HealthResponse type', () => {
    const response: HealthResponse = { status: 'ok' };
    expect(response.status).toBe('ok');
  });
});
`,

  'packages/config/package.json': JSON.stringify({
    name: '@workspace/config',
    version: '0.1.0',
    type: 'module',
    main: './dist/index.js',
    types: './dist/index.d.ts',
    scripts: {
      typecheck: 'tsc --noEmit',
      test: 'vitest run',
      build: 'tsc',
    },
    devDependencies: {
      '@types/node': '^22.0.0',
      typescript: typescriptVersion,
      vitest: vitestVersion,
    },
  }, null, 2) + '\n',

  'packages/config/tsconfig.json': JSON.stringify({
    compilerOptions: {
      target: 'ES2022',
      module: 'NodeNext',
      moduleResolution: 'NodeNext',
      lib: ['ES2022'],
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      resolveJsonModule: true,
      isolatedModules: true,
      declaration: true,
      outDir: './dist',
      rootDir: './src',
    },
    include: ['src/**/*'],
  }, null, 2) + '\n',

  'packages/config/vitest.config.ts': `import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'node',
  },
});
`,

  'packages/config/src/index.ts': `export const config = {
  apiPort: Number(process.env.API_PORT ?? 8787),
} as const;
`,

  'packages/config/src/index.test.ts': `import { describe, it, expect } from 'vitest';
import { config } from './index.js';

describe('config', () => {
  it('provides a default API port', () => {
    expect(config.apiPort).toBe(8787);
  });
});
`,

  'packages/ui/package.json': JSON.stringify({
    name: '@workspace/ui',
    version: '0.1.0',
    type: 'module',
    main: './dist/index.js',
    types: './dist/index.d.ts',
    scripts: {
      typecheck: 'tsc --noEmit',
      test: 'vitest run',
      build: 'tsc',
    },
    devDependencies: {
      '@types/react': typesReactVersion,
      react: reactVersion,
      typescript: typescriptVersion,
      vitest: vitestVersion,
    },
  }, null, 2) + '\n',

  'packages/ui/tsconfig.json': JSON.stringify({
    compilerOptions: {
      target: 'ES2022',
      module: 'ESNext',
      moduleResolution: 'Bundler',
      lib: ['ES2022', 'DOM', 'DOM.Iterable'],
      jsx: 'react-jsx',
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      resolveJsonModule: true,
      isolatedModules: true,
      declaration: true,
      outDir: './dist',
      rootDir: './src',
    },
    include: ['src/**/*'],
  }, null, 2) + '\n',

  'packages/ui/vitest.config.ts': `import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'node',
  },
});
`,

  'packages/ui/src/index.tsx': `export function Button({ children, onClick }: { children: React.ReactNode; onClick?: () => void }) {
  return <button onClick={onClick}>{children}</button>;
}
`,

  'packages/ui/src/index.test.tsx': `import { describe, it, expect } from 'vitest';
import { Button } from './index.js';

describe('ui Button', () => {
  it('is defined', () => {
    expect(Button).toBeDefined();
  });
});
`,

  'packages/test-utils/package.json': JSON.stringify({
    name: '@workspace/test-utils',
    version: '0.1.0',
    type: 'module',
    main: './dist/index.js',
    types: './dist/index.d.ts',
    scripts: {
      typecheck: 'tsc --noEmit',
      test: 'vitest run',
      build: 'tsc',
    },
    devDependencies: {
      typescript: typescriptVersion,
      vitest: vitestVersion,
    },
  }, null, 2) + '\n',

  'packages/test-utils/tsconfig.json': JSON.stringify({
    compilerOptions: {
      target: 'ES2022',
      module: 'NodeNext',
      moduleResolution: 'NodeNext',
      lib: ['ES2022'],
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      resolveJsonModule: true,
      isolatedModules: true,
      declaration: true,
      outDir: './dist',
      rootDir: './src',
    },
    include: ['src/**/*'],
  }, null, 2) + '\n',

  'packages/test-utils/vitest.config.ts': `import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'node',
  },
});
`,

  'packages/test-utils/src/index.ts': `export function createTestContext() {
  return { ready: true };
}
`,

  'packages/test-utils/src/index.test.ts': `import { describe, it, expect } from 'vitest';
import { createTestContext } from './index.js';

describe('test-utils', () => {
  it('creates a ready context', () => {
    const ctx = createTestContext();
    expect(ctx.ready).toBe(true);
  });
});
`,
};

for (const [rel, content] of Object.entries(files)) {
  write(rel, content);
}

console.log(`Generated ${Object.keys(files).length} starter template files.`);
